imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        php:
            version: 8.2
    nodes:
        my-tests:
            tests:
                override:
                    -
                        # command: "composer phpunit"
                        command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                        coverage:
                            file: "build/coverage.clover"
                            format: "php-clover"
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    